# Deploy with:
# serverless deploy --aws-profile park-envs

service: clean-unused-elastic-ips

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  iamRoleStatements:
    #ec2 actions
    - Effect: 'Allow'
      Action:
        - 'ec2:*'
      Resource: '*'

functions:
  cleanip:
    handler: handler.cleanip
    cron:  # Setup scheduled trigger with cron expression
      active: true
      # 17:05 every Friday
      value: '5 17 * * 5'
